# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :CI do
   run_tests(project: "TEST-CI.xcodeproj",
             devices: ["iPhone 15 Pro"],
             code_coverage: true,
             scheme: "TEST-CI",
             output_directory: "test-reports/",
             output_types: "junit")
  end
end
